name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: v1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Agent
        run: |
          GOOS=linux GOARCH=amd64 go build -o bin/tcping-agent-linux-amd64 ./agent/main.go
          chmod +x bin/tcping-agent-linux-amd64

      - name: Build Dashboard
        run: |
          GOOS=linux GOARCH=amd64 go build -o bin/tcping-dashboard-linux-amd64 ./dashboard/main.go
          chmod +x bin/tcping-dashboard-linux-amd64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: |
            bin/tcping-agent-linux-amd64
            bin/tcping-dashboard-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
